### PR TITLE
change request api version to latest

### PR DESCRIPTION
**Pull request by jleifeld**

### CODE REVIEW

**Comment by klarstil** [comment]
Personally I'm not a big fan of changing the API version this many times. As a proposal to solve the problem we should come up with an environment / config variable which contains the API version the test platform should use. 

This way the project which uses this package can define the version they would like to use instead of constantly bumping up the API version in the URLs itself.

See:
- https://docs.cypress.io/guides/guides/environment-variables.html#Setting

**Comment by leichteckig** [comment]
I like @klarstil 's idea. :+1: In my opinion, we should consider this usage of `env` variables. 

For better understanding, why do we want to set the API version back to `v1` after all? My last information was setting it completely independent using `**` notation.

**Comment by jleifeld** [comment]
I set it back just for Request Calls. You can´t request the api with version `**`

**Comment by jleifeld** [comment]
Lets create a ticket for this to build a clean solution and use this as a quickfix?

**Comment by leichteckig** [comment]
Ah, got it. We'll take this PR as quick fix and implement the clean solution in another ticket asap.

**Pull request merged**
